(defun integrate (expr var)
  (cond ((numberp expr)
            `(* ,expr ,var)) 
        ((symbolp expr)
         `(/ (^ ,expr 2) 2)
         )
        ((isPow expr var)
         `(/ (,(car expr) ,(cadr expr) ,(+ 1 (caddr expr))) ,(+ 1 (caddr expr)))
         ) 
        ((eq '+ (car expr))
         `(+ ,(integrate (cadr expr) var) ,(integrate (caddr expr) var))
         )
        ((eq '* (car expr))
         (if (numberp (caddr expr))
           `(*  ,(integrate (cadr expr) var) ,(caddr expr))
           )
         )
        )
  )

(defun isPow (expr var)
  (and (eq (car expr) '^) (eq (cadr expr) var) (numberp (caddr expr)))
  )
